### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by kytrinyx** [comment]
We're aiming for a max-width of 40 characters, so we're probably going to want to update this one.

**Comment by m-a-ge** [comment]
@kytrinyx, how about this?
```groovy
class Greeter {
  def name
     
  Greeter(String name) {
    this.name = name       
  }
     
  def greet() {
    print "Hello, ${name}!"
  }
}
new Greeter('World').greet()
```

**Comment by kytrinyx** [comment]
Yeah, I like it. I'll update the PR. Thanks!

**Comment by kytrinyx** [comment]
Updated.

**Comment by m-a-ge** [comment]
Merged, thanks for the PR!

**Pull request merged**
