### PR TITLE
Key features

### PR DESCRIPTION
**Pull request by artamonovkirill**
Following [Groovy official website](https://groovy-lang.org/).

### CODE REVIEW

**Comment by artamonovkirill** [comment]
@ErikSchierboom I don't know if it's a coincidence, or if 6 is a default number to define language features, but the official Groovy site lists exactly 6 features of the language.

* Would it be a good idea to copy-paste those to Excercism Groovy track? Is there some way to have attribution or a link to the official website in config.json or somewhere else in the Excercism Groovy track?
* I re-worded some features content to fix under 100 characters. Any feedback there?
* Where do I find the available icons? If we go for the "features from the official website" approach, there are already some icons, I just need to find close-enough ones in Excersim icons/

**Review by ErikSchierboom — APPROVED** [review]
> @ErikSchierboom I don't know if it's a coincidence, or if 6 is a default number to define language features, but the official Groovy site lists exactly 6 features of the language.

A happy little coincidence I think :)

> ? Would it be a good idea to copy-paste those to Excercism Groovy track? Is there some way to have attribution or a link to the official website in config.json or somewhere else in the Excercism Groovy track?
> I re-worded some features content to fix under 100 characters. Any feedback there?

We only support this at the track-level at the moment. Is there a license defined for the Groovy website?

> Where do I find the available icons? If we go for the "features from the official website" approach, there are already some icons, I just need to find close-enough ones in Excersim icons/

We will be creating the icons once we have a lot of tracks define their key features, so you can ignore them for now.

**Comment by artamonovkirill** [comment]
> Is there a license defined for the Groovy website?

Yes, there's [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0.html) in the footer.

**Comment by iHiD** [comment]
To attribute per the licence, you'd need to :
- Add the apache licence to the track repo
- Add a note in the track's README.md about this.

I'm not sure it's hugely worth doing for information like this if you're rewording, as it's so "generic" (e.g. you'll probably find similar things on a load of other websites). So I'd maybe just add a link in the README pointing back to the website?

**Comment by artamonovkirill** [comment]
@iHiD I've added a link to the Groovy website in the README. Not sure if that's exactly what you had in mind.

> if you're rewording
"rewording" is an overstatement - the features description is still 70-80% the same, and titles are probably 95% the same.

**Comment by kytrinyx** [comment]
It looks like this PR stalled a bit... possibly through indecision.

My recommendation would be to reword these so that we don't have to worry about attribution and licensing.
I added some icons (from the "Key features" section on this docs page: https://exercism.org/docs/building/tracks/config-json).

We don't have to use the same 6 features listed on the Groovy homepage, we just need 6 things that entice people enough to try the language.

Some suggestions (I don't feel strongly about any of these):

- Readable and concise; easy to learn if coming from Java
- Interoperable with Java; integrates seamlessly with the Java ecosystem
- Powerfully expressive; write domain-specific languages for readable business rules
- Safe and fast; Powerful language features including meta-programming, type inference and static compilation

**Comment by kytrinyx** [comment]
I rebased against main so that Configlet could comfortably lint.

**Pull request merged**
