### PR TITLE
Ported The rotational-cipher exercise from Java

### PR DESCRIPTION
**Pull request by Raibaz**
The reference implementation uses some magic numbers since doing character arithmetic in groovy seems to be pretty tricky, so I added some comments and a reference to asciitable.com

This should fix issue #82.

### CODE REVIEW

**Comment by m-a-ge** [comment]
@Raibaz could you please sync with the current changes in `master` (#95 was merged) to simplify review process

**Comment by Raibaz** [comment]
Yep will do right after Christmas :)

**Comment by Raibaz** [comment]
Sorry, it took me a while, should be ok now.

**Comment by m-a-ge** [comment]
@Raibaz, thanks for your contribution!

All tests passed:
```
RotationalCipherSpec > rotate single character by 1 PASSED
RotationalCipherSpec > rotate single character by 26 PASSED
RotationalCipherSpec > rotate single character by 0 PASSED
RotationalCipherSpec > rotate single character with wrap around PASSED
RotationalCipherSpec > rotate capital letters PASSED
RotationalCipherSpec > rotate spaces PASSED
RotationalCipherSpec > rotate numbers PASSED
RotationalCipherSpec > rotate punctuation PASSED
RotationalCipherSpec > rotate all letters PASSED
:exercises/rotational-cipher:check
:exercises/rotational-cipher:build
```
Merged

**Pull request merged**
