### PR TITLE
Fix CI Gradle builds

### PR DESCRIPTION
**Pull request by artamonovkirill**
* move main `build.gralde` to project root => no need to pass extra argument to Gradle, just `./gradlew b` works
* migrate wrappers to latest Gradle

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
LGTM Did you check to see if the updated exercises still work with the test runner (https://github.com/exercism/groovy-test-runner/)?

**Comment by artamonovkirill** [comment]
> LGTM Did you check to see if the updated exercises still work with the test runner (https://github.com/exercism/groovy-test-runner/)?

@ErikSchierboom , no, I haven't checked if it builds with the test running.

I don't think it would cause an issue since I didn't use any Gradle 7 features.

Is there a specific reason to base `groovy-test-runner` image on Gradle and not on just openjdk/adoptopenjdk and use a Gradle wrapper?

Every Groovy exercise has a Gradle wrapper already. We can ensure that it's also present for newly added exercises.

Of course, it incurs some extra traffic to download the correct Gradle version.

Would that be a problem for Exercism?

**Comment by ErikSchierboom** [comment]
> Is there a specific reason to base groovy-test-runner image on Gradle and not on just openjdk/adoptopenjd, using the Gradle wrapper from the exercises?

No, not that I know of.

> Every Groovy exercise has a Gradle wrapper already. We can ensure that it's also present for newly added exercises.
> Of course, it incurs some extra traffic to download the correct Gradle version.
> Would that be a problem for Exercism?

The test runner operates in a non-networked mode, so it depends on an already pre-installed Gradle version. As for students, I assume the correct Gradle version would only need to be downloaded once?

**Comment by artamonovkirill** [comment]
@ErikSchierboom , tested the build on the same image as gradle-test-runner base:
```
⋊> ~/w/e/s/groovy on fix/ci-build ⨯ docker run -it -v ~/workspace/exercism/sources/groovy:/groovy gradle:6.3.0-jdk11 bash                                                               21:06:04
root@e82a03948644:/home/gradle# cd /groovy
root@e82a03948644:/groovy# gradle test --quiet
root@e82a03948644:/groovy# echo $?
0
```

So, it works fine.

I'll also comment on https://github.com/exercism/groovy-test-runner/issues/3 regarding Gradle versions and dependency management.

**Comment by ErikSchierboom** [comment]
@artamonovkirill I don't see the test runner being run in your example, but maybe I'm missing something? What I did to check, is checked out this PR and then ran `./bin/run-in-docker.sh leap /home/erik/exercism/groovy/leap /home/erik/exercism/groovy/leap`. The `results.json` file in the `/home/erik/exercism/groovy/leap` dir looks good, so 👍

**Comment by ErikSchierboom** [comment]
@artamonovkirill Could you also update the test exercises in the groove-test-runner dir to match the structure introduced in this PR? See https://github.com/exercism/groovy-test-runner/tree/main/tests for the exercises.

**Comment by artamonovkirill** [comment]
> @artamonovkirill I don't see the test runner being run in your example, but maybe I'm missing something? What I did to check, is checked out this PR and then ran `./bin/run-in-docker.sh leap /home/erik/exercism/groovy/leap /home/erik/exercism/groovy/leap`. The `results.json` file in the `/home/erik/exercism/groovy/leap` dir looks good, so 👍

@ErikSchierboom , indeed, I did something slightly different - I've checked that the project itself could be built with older Gradle version.

Just to get the Gradle version question off the table (since it's actually not related to making CI job green) and to have the PR smaller, I've reverted Gradle version change.

The Gradle version can be updated later, post V3 probably - both for this repo and the runner repo.

**Comment by ErikSchierboom** [comment]
@artamonovkirill Nevermind, I completely misread the modified files 🤦 I thought the gradle files of the exercises were updated, but they're not. Sorry!

**Comment by artamonovkirill** [comment]
> @artamonovkirill Nevermind, I completely misread the modified files 🤦 I thought the gradle files of the exercises were updated, but they're not. Sorry!

That's why I reverted the Gradle version change - with all the changes to wrapper-related files (`gradlew`, `gradlew.bat`, `gradle-wrapper.jar` and `gradle-wrapper.properties`) cluttering the view it was hard to see the actual change.

Is there something pending still or can this PR be merged? I'd like to get the CI back to green so that breaking changes do not go unnoticed (like moving exercises to "practice" folder without updating `settings.gradle`).

**Comment by ErikSchierboom** [comment]
This can be merged!

**Comment by artamonovkirill** [comment]
@ErikSchierboom I don't have the permissions. Can you merge it, please?

**Comment by ErikSchierboom** [comment]
@artamonovkirill Done!

**Pull request merged**
